Repository octokit/webhooks-methods.js, pull requests merged in 2023-06, with the labels that each got.

#159 fix(build): switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  src/node/sign.ts
  src/web.ts
  test/browser-test.js
  tsconfig.json
Labels: Type: Maintenance

#161 Remove pika and add tsconfig.test.json
  package-lock.json
  package.json
  test/tsconfig.test.json
Labels: Type: Maintenance

#157 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
  scripts/build.mjs
Labels: Type: Maintenance, Type: Breaking change

#163 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
